---
keyfile_data: ${keyfile_data}
avi_default_pass: ${avi_default_pass}
password: ${password}
api_version: ${api_version}
gcp_region: ${gcp_region}
se_project_id: ${se_project_id}
frontend_data_vpc_subnet_name: ${frontend_data_vpc_subnet_name}
management_vpc_subnet_name: ${management_vpc_subnet_name}
backend_data_vpc_subnet_name: ${backend_data_vpc_subnet_name}
frontend_data_vpc_network_name: ${frontend_data_vpc_network_name}
management_vpc_network_name: ${management_vpc_network_name}
backend_data_vpc_network_name: ${backend_data_vpc_network_name}
worker_cidr: ${worker_cidr}
backend_se_gw: ${backend_se_gw}
vip_network_cidr: ${vip_network_cidr}
domain_name: ${domain_name}
se_machine_type: ${se_machine_type}
gke_pod_cidr: ${gke_pod_cidr}
