apiVersion: apps/v1
kind: Deployment
metadata:
  name: hackazon
spec:
  selector:
    matchLabels:
      app: hackazon
  replicas: 1 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: hackazon
    spec:
      containers:
      - name: hackazon
        image: ianwijaya/hackazon
        ports:
        - containerPort: 80
        - containerPort: 443
---
kind: Service
apiVersion: v1
metadata:
  name: hackazon
spec:
  selector:
    app: hackazon
  ports:
  - protocol: TCP
    name: http
    port: 80
    nodePort: 30080
  - protocol: TCP
    name: https
    port: 443
    nodePort: 30443
  type: NodePort
---
apiVersion: v1
kind: Secret
metadata:
  name: hackazon-tls
  namespace: default
data:
  tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUQwekNDQXJ1Z0F3SUJBZ0lVRUNwRzlweGJtYzhUQkZBbXZxY2xXYUFvVzRrd0RRWUpLb1pJaHZjTkFRRUwKQlFBd2VURUxNQWtHQTFVRUJoTUNRMEV4Q3pBSkJnTlZCQWdNQWs5T01SQXdEZ1lEVlFRSERBZFViM0p2Ym5SdgpNUnN3R1FZRFZRUUtEQkpXVFhkaGNtVWdRMkZ1WVdSaElFbHVZeTR4R2pBWUJnTlZCQXNNRVVGMmFTQk9aWFIzCmIzSnJjeUJKYm1NdU1SSXdFQVlEVlFRRERBbHpaV04xY21VdGJXVXdIaGNOTWpBd09URTJNVFkxTVRBeFdoY04KTWpFd09URTJNVFkxTVRBeFdqQjVNUXN3Q1FZRFZRUUdFd0pEUVRFTE1Ba0dBMVVFQ0F3Q1QwNHhFREFPQmdOVgpCQWNNQjFSdmNtOXVkRzh4R3pBWkJnTlZCQW9NRWxaTmQyRnlaU0JEWVc1aFpHRWdTVzVqTGpFYU1CZ0dBMVVFCkN3d1JRWFpwSUU1bGRIZHZjbXR6SUVsdVl5NHhFakFRQmdOVkJBTU1DWE5sWTNWeVpTMXRaVENDQVNJd0RRWUoKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBT1lxRW40QjRhMHpqUzZ5N3Y1Q0JrZDJaeHNtK2swdAoyUGxoVy9GcURTNy8vbG9tOXlWUzhJdFU5cUI3VXJZVjNLd213K3lvL3dmNE9wUndNL1M1YWlMenFLWXl6N0JQClVKY3Z0Mlg4ZmRiazhWL1UvUCt1NGVJVS9Ed0x3RzJyUnV2a1RMSDc3bFRJM1J0aUx0YVVOM1dsZHZMS0o0dVkKZXZRNXJJT1lsMGxCV0xKM0xQU1B3cFlxYlBjTm92T2hUZElrUy8wbWQ4ZnBUQ3ROS3VROHl4TWdmS0JjRVZUQgpBWVEwL2FlcEpRYmw2OGpLZTFmTWdUMEdNKzNaY3c0QXR0Qk1xV2xSN1QrR3BVc2VscVlZZEtPM1Nwa2h0eDhsCkVxcVRzUVR6OFNpdEt4SnIrRktQUlJ0bWJ2c1IwbmlkeDZUWlBQdmFxYmVSbmh2L0FKaFA5bzBDQXdFQUFhTlQKTUZFd0hRWURWUjBPQkJZRUZFc1drZ0pLRHhoZjlwbVUzRkxTRVdhZE9pV3RNQjhHQTFVZEl3UVlNQmFBRkVzVwprZ0pLRHhoZjlwbVUzRkxTRVdhZE9pV3RNQThHQTFVZEV3RUIvd1FGTUFNQkFmOHdEUVlKS29aSWh2Y05BUUVMCkJRQURnZ0VCQUszUzRhNk5wTUxHQnZqNHRJcitaeU1pcjdDWXoxb0k2Q3RzL3owTkFIdFNpVGZ4RTlvV0htU0wKcHJHeWRmL1ZqOEVqU09raUVpTXBBUGFOTno4RFZGZVY1anhhMHBNQ25tekltWWg4dFllT2R0dFVIbXBmOVdtMgpyVGs2QlhBVEVLM01Fc1Z4N1dNdFVkQjM0UmxXa2g0cVhlNHFIaUdTT0tUV3lTMkRSMlRvOGZMVmU2VzNzZkhBClVzTW12aC9TVmhoMHg3MGJLdEpNUWdJV3M3dUlDeGM1SDdabUhERVFNZHpUajg1MGZBeGlyNlBtcWk1N0dJLzEKb05xUVZxTUQxQ2thajdRK2FERGgxTnFOQysycDFGa0NjV09QZTZJNFljbkY3bXhIMjQwZzZYL2s0cUtPWk9lTQpqcGlGbnp1VjdPUk4vT0M4OEd3QW8rRHdTeCs2Q0xzPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
  tls.key: LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JSUV2d0lCQURBTkJna3Foa2lHOXcwQkFRRUZBQVNDQktrd2dnU2xBZ0VBQW9JQkFRRG1LaEorQWVHdE00MHUKc3U3K1FnWkhkbWNiSnZwTkxkajVZVnZ4YWcwdS8vNWFKdmNsVXZDTFZQYWdlMUsyRmR5c0pzUHNxUDhIK0RxVQpjRFAwdVdvaTg2aW1Ncyt3VDFDWEw3ZGwvSDNXNVBGZjFQei9ydUhpRlB3OEM4QnRxMGJyNUV5eCsrNVV5TjBiCllpN1dsRGQxcFhieXlpZUxtSHIwT2F5RG1KZEpRVml5ZHl6MGo4S1dLbXozRGFMem9VM1NKRXY5Sm5mSDZVd3IKVFNya1BNc1RJSHlnWEJGVXdRR0VOUDJucVNVRzVldkl5bnRYeklFOUJqUHQyWE1PQUxiUVRLbHBVZTAvaHFWTApIcGFtR0hTanQwcVpJYmNmSlJLcWs3RUU4L0VvclNzU2EvaFNqMFViWm03N0VkSjRuY2VrMlR6NzJxbTNrWjRiCi93Q1lUL2FOQWdNQkFBRUNnZ0VCQUxJN2xrSlp0cWJuS3NjazdRbWJtejB2cFR4VGZMVFRjaGY3bXJWaHlIL0MKNFBaekFpTzNER3I1Q2xyUDVRYjMrd0NjckUvUnRsdzNqelZ2aGV4V3dLZjhRM2NnRmRDVU92WTRqeTY4emIzaApZRUV6c0E5WEg3aHhRN3BENTJtRm50QUE1SnRYV2dIeDRiYlkyeWh6Y2xiNklSaDJEeFY4cUlvRE4ySllnWjdKCk1aOE54SWRqeWVyVkxJbFdHRzlkMGhudUtqNnBOeDRHMVlneWJCaWtZTjZUOERpUjBUQVFZdXRuaXFIUDVLdWMKSkRiMllNekJ5RUlDNzliMGxGSVB6VWhUVFFrbUlSbU5uWE50TGYxYTRXNFdpU296U3lFUU1JeEEwdkpvWnQ0Swp0Uno2ZUUxOUtmK0FXbGZyd01wQW5ZT2p0OFlWMmROVFB2c0FjdWl1SUFFQ2dZRUE5Nkcrd05Dd05BSkNSK2tBCjUwdWhGRGcyczc1aWNra2JnODRyYjBRdFpZOUh5K1o4YWsrTnYrM2l0WVRDSGM3dVJ5ajBseC9IdzJMR1dZaHIKQ2RPUjdFRFlWRWJ2YkFuWFJyTkllSHcrWXRKWWk2QktSL2FIRllZbWtFTnZ4WjMySUhRMG5QcjByaUdFd29nOQowN1MwQ2VGSXlJMEF4SE5uaVRZNGdJWEZ0QUVDZ1lFQTdmRTNjTjJxSkJRZzJLUUdVKy8yU2xSZGlhY2RsR2U0Cm9RTkZyL3pWU2N2dm5pdWlIM01KcDlqVmJKbWMrWlRNbUhqVy9ncERjcG9wQU1Zb3l2UTNDMmpoNnozS01kKy8KQXhBOTBueFZHTk1ZYm9WeDdPYnNWRTVnemJya0xYSkZ0YW0xbHdHOTdFQ1V4MUEwQzdxc3dhV1RGTEZKZE45ZgpoNlVVWXFERDBvMENnWUVBc2F0Ri9uZDhoTVErSS9RRUp1ODNVaGVHLysyUUdxbGphVzBKOHRuNnJFeGgyZVN6CnpWN291QlVJdk8zVWpLaUVnMS9hSlhleXp2ZldralJ6ZitoaFlSMmhXTTVRUjdiRDAwRWN0UDJIa1VXVUxCSEUKV2QrQ1Npb25Ed2lqY0NrR2g0QjRvMHpYTXZ4dmtWZEk3TlZRKzJtODI4OTNCbnc2ZzlMNE5SWkZwQUVDZ1lFQQpxVnNFOE9wMHpSVWVnOVBMUlRjSWY4TW9pRzlQMkc4eXREZVdCRHJhdkpuUXhTMmRTUEVpTUR0ZlBOcmhKYXRKCkxFVG1FUTdSRHVLMnlIeENVS0llQTVyMUlmQnExN0MvVGJqanA4c2k3blpoYjFpL3k3UlpCWEI3NmpKWmNoZGgKa25sbWJFS3JJVnFlQ25jRmRFdTc1bUNwSFJOS2kwcnB2YXc3cEM5MDhZa0NnWUFWbnRUTXlDTElhWlFkYWNiUgo5K01OY3JkMVkySk4zMEs0RTFGV01jMzRxR0JSaExXa2liR1VhbFZQa0hxSCtYSzJEemRYRHBYSGUyWENwdzBTCnZGbDFmUGJVODdWTDRSSmVOaXNNTTJrMFFWM3NRVWl4dkI3eGd2UHlqSTR1KzdTaG56V1JjcDZ2dlVoaGJ1bFQKM2FQams0ajRQUTdXclFVVGsvVjI4d01iVWc9PQotLS0tLUVORCBQUklWQVRFIEtFWS0tLS0tCg==
type: kubernetes.io/tls
