apiVersion: apps/v1
kind: Deployment
metadata:
  name: juice
spec:
  selector:
    matchLabels:
      app: juice
  replicas: 1 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: juice
    spec:
      containers:
      - name: juice
        image: bkimminich/juice-shop
        ports:
        - containerPort: 3000
---
kind: Service
apiVersion: v1
metadata:
  name: juice
spec:
  selector:
    app: juice
  ports:
  - protocol: TCP
    name: http
    port: 3000
    nodePort: 30003
  type: NodePort
